spring:
  #\u94FE\u63A5\u6570\u636E\u5E93\u914D\u7F6E
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/chat_socket?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
    username: root
    password: 123456
  #\u6570\u636E\u5E93\u6821\u9A8C\u6A21\u5F0F\u548C\u662F\u5426\u63A7\u5236\u53F0\u6253\u5370sql\u8BED\u53E5
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
  #\u8FD4\u56DE\u7684\u65F6\u95F4\u683C\u5F0F\u548C\u65F6\u533A
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
